export const TEAMS = {
  "AE": { id: "AE", name: "Alter Ego ESPORTS", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/ae-64.png" },
  "BTR": { id: "BTR", name: "Bigetron BY VIT", logo: "https://ik.imagekit.io/cy319w8h1/btr_vit.png" },
  "ONIC": { id: "ONIC", name: "ONIC", logo: "https://ik.imagekit.io/cy319w8h1/onic-b-64.png" },
  "DEWA": { id: "DEWA", name: "Dewa United", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/dewa-64.png" },
  "EVOS": { id: "EVOS", name: "EVOS", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/evos-64.png" },
  "TLID": { id: "TLID", name: "Team Liquid ID", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/tlid-64.png" },
  "GEEK": { id: "GEEK", name: "Geek Fam", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/geek-64.png" },
  "RRQ": { id: "RRQ", name: "RRQ HOSHI", logo: "https://ik.imagekit.io/nloe8dhf7w/mplid/s14/teams/rrq-64.png" },
  "NAVI": { id: "NAVI", name: "NAVI", logo: "https://ik.imagekit.io/cy319w8h1/NAVI-2.png" }
};

export const INITIAL_MATCHES = [
  // WEEK 1 
            { week: 1, matchId: "w1_m1", day: "Day1", teamA: "BTR", teamB: "AE", leftScore: 2, rightScore: 1 },
            { week: 1, matchId: "w1_m2", day: "Day1", teamA: "NAVI", teamB: "RRQ", leftScore: 2, rightScore: 0 },
            { week: 1, matchId: "w1_m3", day: "Day2", teamA: "EVOS", teamB: "GEEK", leftScore: 2, rightScore: 0 },
            { week: 1, matchId: "w1_m4", day: "Day2", teamA: "AE", teamB: "ONIC", leftScore: 0, rightScore: 2 },
            { week: 1, matchId: "w1_m5", day: "Day2", teamA: "TLID", teamB: "NAVI", leftScore: 2, rightScore: 1 },
            { week: 1, matchId: "w1_m6", day: "Day3", teamA: "DEWA", teamB: "BTR", leftScore: 2, rightScore: 0 },
            { week: 1, matchId: "w1_m7", day: "Day3", teamA: "EVOS", teamB: "TLID", leftScore: 0, rightScore: 2 },
            { week: 1, matchId: "w1_m8", day: "Day3", teamA: "RRQ", teamB: "ONIC", leftScore: 0, rightScore: 2 },
            // WEEK 2 
            { week: 2, matchId: "w2_m1", day: "Day1", teamA: "ONIC", teamB: "GEEK", leftScore: 2, rightScore: 0 },
            { week: 2, matchId: "w2_m2", day: "Day1", teamA: "DEWA", teamB: "NAVI", leftScore: 2, rightScore: 0 },
            { week: 2, matchId: "w2_m3", day: "Day2", teamA: "GEEK", teamB: "BTR", leftScore: 2, rightScore: 0 },
            { week: 2, matchId: "w2_m4", day: "Day2", teamA: "AE", teamB: "EVOS", leftScore: 2, rightScore: 1 },
            { week: 2, matchId: "w2_m5", day: "Day2", teamA: "TLID", teamB: "DEWA", leftScore: 2, rightScore: 1 },
            { week: 2, matchId: "w2_m6", day: "Day3", teamA: "NAVI", teamB: "AE", leftScore: 1, rightScore: 2 },
            { week: 2, matchId: "w2_m7", day: "Day3", teamA: "RRQ", teamB: "TLID", leftScore: 0, rightScore: 2 },
            { week: 2, matchId: "w2_m8", day: "Day3", teamA: "BTR", teamB: "EVOS", leftScore: 2, rightScore: 1 },
            // WEEK 3
            { week: 3, matchId: "w3_m1", day: "Day1", teamA: "ONIC", teamB: "DEWA", leftScore: 2, rightScore: 1 },
            { week: 3, matchId: "w3_m2", day: "Day1", teamA: "NAVI", teamB: "EVOS", leftScore: 0, rightScore: 2 },
            { week: 3, matchId: "w3_m3", day: "Day2", teamA: "TLID", teamB: "GEEK", leftScore: 0, rightScore: 2 },
            { week: 3, matchId: "w3_m4", day: "Day2", teamA: "ONIC", teamB: "BTR", leftScore: 1, rightScore: 2 },
            { week: 3, matchId: "w3_m5", day: "Day2", teamA: "RRQ", teamB: "AE", leftScore: 1, rightScore: 2 },
            { week: 3, matchId: "w3_m6", day: "Day3", teamA: "BTR", teamB: "NAVI", leftScore: 1, rightScore: 2 },
            { week: 3, matchId: "w3_m7", day: "Day3", teamA: "GEEK", teamB: "RRQ", leftScore: 2, rightScore: 1 },
            { week: 3, matchId: "w3_m8", day: "Day3", teamA: "AE", teamB: "DEWA", leftScore: 0, rightScore: 2 },
            // WEEK 4
            { week: 4, matchId: "w4_m1", day: "Day1", teamA: "NAVI", teamB: "ONIC", leftScore: 0, rightScore: 2 },
            { week: 4, matchId: "w4_m2", day: "Day1", teamA: "EVOS", teamB: "DEWA", leftScore: 2, rightScore: 0 },
            { week: 4, matchId: "w4_m3", day: "Day2", teamA: "TLID", teamB: "BTR", leftScore: 1, rightScore: 2 },
            { week: 4, matchId: "w4_m4", day: "Day2", teamA: "RRQ", teamB: "EVOS", leftScore: 0, rightScore: 2 },
            { week: 4, matchId: "w4_m5", day: "Day2", teamA: "GEEK", teamB: "AE", leftScore: 1, rightScore: 2 },
            { week: 4, matchId: "w4_m6", day: "Day3", teamA: "ONIC", teamB: "TLID", leftScore: 2, rightScore: 0 },
            { week: 4, matchId: "w4_m7", day: "Day3", teamA: "BTR", teamB: "RRQ", leftScore: 2, rightScore: 1 },
            { week: 4, matchId: "w4_m8", day: "Day3", teamA: "DEWA", teamB: "GEEK", leftScore: 2, rightScore: 1 },
            // WEEK 5 
            { week: 5, matchId: "w5_m1", day: "Day1", teamA: "GEEK", teamB: "NAVI", leftScore: 0, rightScore: 2 },
            { week: 5, matchId: "w5_m2", day: "Day1", teamA: "EVOS", teamB: "ONIC", leftScore: 0, rightScore: 2 },
            { week: 5, matchId: "w5_m3", day: "Day2", teamA: "DEWA", teamB: "RRQ", leftScore: 2, rightScore: 0 },
            { week: 5, matchId: "w5_m4", day: "Day2", teamA: "AE", teamB: "TLID", leftScore: 1, rightScore: 2 },
            { week: 5, matchId: "w5_m5", day: "Day2", teamA: "EVOS", teamB: "BTR", leftScore: 0, rightScore: 2 },
            { week: 5, matchId: "w5_m6", day: "Day3", teamA: "AE", teamB: "NAVI", leftScore: 2, rightScore: 1 },
            { week: 5, matchId: "w5_m7", day: "Day3", teamA: "GEEK", teamB: "ONIC", leftScore: 2, rightScore: 1 },
            { week: 5, matchId: "w5_m8", day: "Day3", teamA: "DEWA", teamB: "TLID", leftScore: 2, rightScore: 0 },
            // WEEK 6 
            { week: 6, matchId: "w6_m1", day: "Day1", teamA: "NAVI", teamB: "DEWA", leftScore: 1, rightScore: 2 },
            { week: 6, matchId: "w6_m2", day: "Day1", teamA: "AE", teamB: "GEEK", leftScore: 2, rightScore: 1 },
            { week: 6, matchId: "w6_m3", day: "Day2", teamA: "EVOS", teamB: "AE", leftScore: 2, rightScore: 1 },
            { week: 6, matchId: "w6_m4", day: "Day2", teamA: "TLID", teamB: "ONIC", leftScore: 0, rightScore: 2 },
            { week: 6, matchId: "w6_m5", day: "Day2", teamA: "RRQ", teamB: "BTR", leftScore: 2, rightScore: 0 },
            { week: 6, matchId: "w6_m6", day: "Day3", teamA: "NAVI", teamB: "TLID", leftScore: 1, rightScore: 2 },
            { week: 6, matchId: "w6_m7", day: "Day3", teamA: "ONIC", teamB: "RRQ", leftScore: 2, rightScore: 0 },
            { week: 6, matchId: "w6_m8", day: "Day3", teamA: "GEEK", teamB: "EVOS", leftScore: 2, rightScore: 0 },
            // WEEK 7
            { week: 7, matchId: "w7_m1", day: "Day1", teamA: "GEEK", teamB: "DEWA", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m2", day: "Day1", teamA: "BTR", teamB: "TLID", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m3", day: "Day2", teamA: "DEWA", teamB: "AE", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m4", day: "Day2", teamA: "EVOS", teamB: "RRQ", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m5", day: "Day2", teamA: "ONIC", teamB: "NAVI", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m6", day: "Day3", teamA: "RRQ", teamB: "GEEK", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m7", day: "Day3", teamA: "NAVI", teamB: "BTR", leftScore: 0, rightScore: 0 },
            { week: 7, matchId: "w7_m8", day: "Day3", teamA: "TLID", teamB: "EVOS", leftScore: 0, rightScore: 0 },
            // WEEK 8
            { week: 8, matchId: "w8_m1", day: "Day1", teamA: "BTR", teamB: "GEEK", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m2", day: "Day1", teamA: "DEWA", teamB: "ONIC", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m3", day: "Day2", teamA: "EVOS", teamB: "NAVI", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m4", day: "Day2", teamA: "TLID", teamB: "RRQ", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m5", day: "Day2", teamA: "ONIC", teamB: "AE", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m6", day: "Day3", teamA: "DEWA", teamB: "EVOS", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m7", day: "Day3", teamA: "AE", teamB: "BTR", leftScore: 0, rightScore: 0 },
            { week: 8, matchId: "w8_m8", day: "Day3", teamA: "RRQ", teamB: "NAVI", leftScore: 0, rightScore: 0 },
            // WEEK 9
            { week: 9, matchId: "w9_m1", day: "Day1", teamA: "BTR", teamB: "DEWA", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m2", day: "Day1", teamA: "TLID", teamB: "AE", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m3", day: "Day2", teamA: "GEEK", teamB: "TLID", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m4", day: "Day2", teamA: "AE", teamB: "RRQ", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m5", day: "Day2", teamA: "BTR", teamB: "ONIC", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m6", day: "Day3", teamA: "RRQ", teamB: "DEWA", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m7", day: "Day3", teamA: "ONIC", teamB: "EVOS", leftScore: 0, rightScore: 0 },
            { week: 9, matchId: "w9_m8", day: "Day3", teamA: "NAVI", teamB: "GEEK", leftScore: 0, rightScore: 0 }
        ];
